/* INSERCIONES TIPO PRODUCTO */
INSERT INTO producto_tipos(codigo, descripcion) VALUES ('DIA', 'Diarios');
INSERT INTO producto_tipos(codigo, descripcion) VALUES ('RVT', 'Revistas');
INSERT INTO producto_tipos(codigo, descripcion) VALUES ('OPC', 'Opcionales');

/* INSERCIONES CATEGORIA PRODUCTO */
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('BRA', 'Familia Brando');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('DJR', 'Familia Disney Junior');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('DPR', 'Familia Disney Princesas');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('FAS', 'Familia Fascículos');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('HOL', 'Familia Hola');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('JAR', 'Familia Jardín');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('LIV', 'Familia Living');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('LNA', 'Familia La Nación');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('LUG', 'Familia Lugares');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('OHL', 'Familia Ohlalá');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('RST', 'Familia Rolling Stone');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('AMB', 'Familia Ámbito');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('CRO', 'Familia El Cronista');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('POP', 'Familia Popular');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('ELT', 'Familia El Tribuno');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('UNO', 'Familia El Uno');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('VER', 'Familia Vertice');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('ELP', 'Familia El País');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('TAR', 'Familia Tiempo Argentino');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('TAP', 'Familia Tapas');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('PAG', 'Familia Pagina 12');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('SHT', 'One Shot');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('PLA', 'Opcionales Ed. Planeta');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('APE', 'REVISTA APERTURA CRONISTA');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('PRH', 'Pengüin Random House');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('SUS', 'Susana');
INSERT INTO producto_categorias(codigo, descripcion) VALUES ('GEN', 'Generico');

/* INSERCIONES SUBCATEGORIA PRODUCTO */
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('ANU', 'ANUARIO');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('BOK', 'BOOKAZINE');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('CAL', 'CALENDARIO');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('DOM', 'DOMINGO');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('LUN', 'LUNES');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('MAR', 'MARTES');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('MIE', 'MIERCOLES');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('JUE', 'JUEVES');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('VIE', 'VIERNES');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('SAB', 'SABADO');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('ESP', 'ESPECIAL');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('LIB', 'LIBRO');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('MEN', 'MENSUAL');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('QUI', 'QUINCENAL');
INSERT INTO producto_subcategorias(codigo, descripcion) VALUES ('SEM', 'SEMANAL');

/* INSERCIONES Tabla Pivot producto_categorias_producto_tipo_links */
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (8,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (12,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (13,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (14,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (15,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (16,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (18,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (19,1);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (21,1);								

INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (1,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (2,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (3,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (5,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (6,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (7,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (9,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (10,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (11,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (27,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (22,2);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (25,2);

INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (17,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (20,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (22,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (23,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (24,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (26,3);							
INSERT INTO producto_categorias_producto_tipo_links (producto_categoria_id , producto_tipo_id) VALUES (28,3);

/* Tabla Pivot producto_categorias_producto_subcategorias_links */
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (8,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (12,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (13,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (14,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (15,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (16,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (18,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (19,10);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,4);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,5);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,6);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,7);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,8);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,9);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (21,10);												

INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (1,15);
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (2,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (3,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (5,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (6,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (7,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (9,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (10,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (11,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (27,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,12);												
--INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,13);												
--INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,14);												
--INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,1);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,2);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,3);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,11);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,12);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (25,15);												

INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (17,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (17,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (17,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (20,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (20,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (20,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (22,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (23,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (23,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (23,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (24,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (24,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (24,15);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (26,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (26,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (26,15);				
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (28,13);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (28,14);												
INSERT INTO producto_categorias_producto_subcategorias_links(producto_categoria_id, producto_subcategoria_id) values (28,15);